require_relative 'sliding_piece'
require_relative 'stepping_piece'
require_relative 'sliding_piece'
require_relative 'sliding_piece'
require_relative 'sliding_piece'
require_relative 'sliding_piece'
require_relative 'sliding_piece'
require_relative 'sliding_piece'
